name: Backend Deploy

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: setup node
        uses: actions/setup-node@v6

      - name: install dependencies
        run: npm ci
        working-directory: backend

      - name: build project
        run: npm run build
        working-directory: backend

      - name: zip artifact
        run: |
          zip -r backend.zip dist package.json package-lock.json
        working-directory: backend

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: upload to s3
        run: aws s3 cp backend.zip s3://portfolio-backend-artifacts-134679/backend.zip
        working-directory: backend

      - name: refresh asg instances
        run: |
          aws autoscaling start-instance-refresh --auto-scaling-group-name portfolio-asg
