name: Worker Deploy

on:
  push:
    branches:
      - main
    paths:
      - "worker/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: zip worker
        run: zip worker.zip index.js
        working-directory: worker

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: update lambda function
        run: |
          aws lambda update-function-code --function-name portfolio-email-worker --zip-file fileb://worker.zip
        working-directory: worker
